kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: gradle:jdk8
  environment:
    SONATYPE_GPG_KEYID:
      from_secret: sonatype_gpg_keyid
    SONATYPE_GPG_PASSWORD:
      from_secret: sonatype_gpg_password
    SONATYPE_USERNAME:
      from_secret: sonatype_username
    SONATYPE_PASSWORD:
      from_secret: sonatype_password
    SONATYPE_GPG_KEY:
      from_secret: sonatype_gpg_key
  commands:
    - echo "signing.keyId=$${SONATYPE_GPG_KEYID}" > ~/.gradle/gradle.properties
    - echo "sonatypeUsername=$${SONATYPE_USERNAME}" > ~/.gradle/gradle.properties
    #- ./gradlew build

- name: stage
  image: gradle:jdk8
  when:
    event: 
      - promote
    target:
      - debug
      - production
  environment:
    SONATYPE_GPG_KEYID:
      from_secret: sonatype_gpg_keyid
    SONATYPE_GPG_PASSWORD:
      from_secret: sonatype_gpg_password
    SONATYPE_USERNAME:
      from_secret: sonatype_username
    SONATYPE_PASSWORD:
      from_secret: sonatype_password
    SONATYPE_GPG_KEY:
      from_secret: sonatype_gpg_key
  commands:
    - echo "signing.keyId=$${SONATYPE_GPG_KEYID}" > ~/.gradle/gradle.properties
    - echo "signing.password=$${SONATYPE_GPG_PASSWORD}" >> ~/.gradle/gradle.properties
    - echo "signing.secretKeyRingFile=$${HOME}/.gradle/secring.gpg" >> ~/.gradle/gradle.properties
    - echo "sonatypeUsername=$${SONATYPE_USERNAME}" >> ~/.gradle/gradle.properties"
    - echo "sonatypePassword=$${SONATYPE_PASSWORD}" >> ~/.gradle/gradle.properties"
    - echo $${SONATYPE_GPG_KEY} | base64 -d > ~/.gradle/secring.gpg
    #- ./gradlew publishToSonatype

- name: deploy
  image: gradle:jdk8
  when:
    event:
      - promote
    target:
      - production
  commands:
    - echo "signing.keyId=${sonatype_gpg_keyid}" > ~/.gradle/gradle.properties
    - echo "signing.password=${sonatype_gpg_password}" >> ~/.gradle/gradle.properties
    - echo "signing.secretKeyRingFile=${HOME}/.gradle/secring.gpg" >> ~/.gradle/gradle.properties
    - echo "sonatypeUsername=${sonatype_username}" >> ~/.gradle/gradle.properties"
    - echo "sonatypePassword=${sonatype_password}" >> ~/.gradle/gradle.properties"
    - ./gradlew closeAndReleaseStagingRepository

