kind: pipeline
type: kubernetes
name: default

steps:

- name: stage
  image: gradle:jdk8
  environment:
    SONATYPE_GPG_KEYID:
      from_secret: sonatype_gpg_keyid
    SONATYPE_USERNAME:
      from_secret: sonatype_username
    SONATYPE_GPG_KEY:
      from_secret: sonatype_gpg_key
    SONATYPE_GPG_PASSWORD:
      from_secret: sonatype_gpg_password
    SONATYPE_PASSWORD:
      from_secret: sonatype_password
  commands:
  - apt-get update && apt-get install --yes --no-install-recommends gnupg2
  - echo "signing.keyId=$${SONATYPE_GPG_KEYID}" > gradle.properties
  - echo "signing.password=$${SONATYPE_GPG_PASSWORD}" >> gradle.properties
  - echo "signing.secretKeyRingFile=$${HOME}/.gnupg/secring.gpg" >> gradle.properties
  - echo "sonatypeUsername=$${SONATYPE_USERNAME}" >> gradle.properties
  - echo "sonatypePassword=$${SONATYPE_PASSWORD}" >> gradle.properties
  - echo "$${SONATYPE_GPG_KEY}" >> private.key
  - echo "$${SONATYPE_GPG_PASSWORD}" | gpg --batch --yes --passphrase-fd 0 --import private.key
  - echo "$${SONATYPE_GPG_PASSWORD}" | gpg --batch --yes --passphrase-fd 0 --export-secret-keys > ~/.gnupg/secring.gpg 
  - gradle --no-daemon publishToSonatype

- name: build
  image: openjdk:8
  commands:
  - ./gradlew

- name: deploy
  image: gradle:jdk8
  when:
    event:
    - promote
    target:
    - production
  commands:
  - echo "signing.keyId=$${sonatype_gpg_keyid}" > gradle.properties
  - echo "signing.password=$${sonatype_gpg_password}" >> gradle.properties
  - echo "signing.secretKeyRingFile=$${HOME}/.gradle/secring.gpg" >> gradle.properties
  - echo "sonatypeUsername=$${sonatype_username}" >> gradle.properties
  - echo "sonatypePassword=$${sonatype_password}" >> gradle.properties
  
  - ./gradlew closeAndReleaseStagingRepository

