kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: gradle:jdk8
  commands:
  - gradle build

- name: stage
  image: gradle:jdk8
  commands:
  - echo "signing.keyId=$${sonatype_gpg_keyid}" > gradle.properties
  - echo "signing.secretKeyRingFile=secring.gpg" >> gradle.properties
  - echo "sonatypeUsername=$${sonatype_username}" >> gradle.properties
  - echo ${sonatype_gpg_key} | base64 -d > secring.gpg
  - pwd
  - cat gradle.properties


- name: deploy
  image: gradle:jdk8
  when:
  event:
  - promote
  target:
  - production
  commands:
  - echo "signing.keyId=$${sonatype_gpg_keyid}" > gradle.properties
  - echo "signing.password=$${sonatype_gpg_password}" >> gradle.properties
  - echo "signing.secretKeyRingFile=${HOME}/.gradle/secring.gpg" >> gradle.properties
  - echo "sonatypeUsername=$${sonatype_username}" >> gradle.properties
  - echo "sonatypePassword=$${sonatype_password}" >> gradle.properties
  
  - ./gradlew closeAndReleaseStagingRepository

