kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: openjdk:8
  commands:
  - ./gradlew

- name: stage
  image: openjdk:8
  environment:
    SONATYPE_GPG_KEYID:
      from_secret: sonatype_gpg_keyid
    SONATYPE_USERNAME:
      from_secret: sonatype_username
    SONATYPE_GPG_KEY:
      from_secret: sonatype_gpg_key
    SONATYPE_GPG_PASSWORD:
      from_secret: sonatype_gpg_password
    SONATYPE_PASSWORD:
      from_secret: sonatype_password
  commands:
  - echo "signing.keyId=$${SONATYPE_GPG_KEYID}" > gradle.properties
  - echo "signing.password=$${SONATYPE_GPG_PASSWORD}" >> gradle.properties
  - echo "signing.secretKeyRingFile=${HOME}/.gnupg/secring.gpg" >> gradle.properties

  - ./gradlew publishToSonatype


- name: deploy
  image: gradle:jdk8
  when:
  event:
  - promote
  target:
  - production
  commands:
  - echo "signing.keyId=$${sonatype_gpg_keyid}" > gradle.properties
  - echo "signing.password=$${sonatype_gpg_password}" >> gradle.properties
  - echo "signing.secretKeyRingFile=${HOME}/.gradle/secring.gpg" >> gradle.properties
  - echo "sonatypeUsername=$${sonatype_username}" >> gradle.properties
  - echo "sonatypePassword=$${sonatype_password}" >> gradle.properties
  
  - ./gradlew closeAndReleaseStagingRepository

