kind: pipeline
type: kubernetes
name: default

steps:
- name: build
  image: gradle:jdk8
  commands:
  - ./gradlew build

- name: stage
  image: gradle:jdk8
  environment:
  ORG_GRADLE_PROJECT_sonatypeUsername:
    from_secret: sonatype_username
  ORG_GRADLE_PROJECT_sonatypePassword:
    from_secret: sonatype_password
  commands:
  - echo "signing.keyId=${sonatype_gpg_keyid}" > ~/.gradle/gradle.properties
  - echo "signing.password=${sonatype_gpg_password}" >> ~/.gradle/gradle.properties
  - echo "signing.secretKeyRingFile=${HOME}/.gradle/secring.gpg" >> ~/.gradle/gradle.properties
  - echo ${sonatype_gpg_key} | base64 -d > ~/.gradle/secring.gpg
  - ./gradlew publishToSonatype
