kind: pipeline
type: kubernetes
name: default

steps:

- name: build
  image: gradle:jdk8
  environment:
    INDICO_TEST_TOKEN: indico_test_token
  commands:
  - ./test.sh

- name: stage
  image: gradle:jdk8
  when:
    branch: 
    - master
    event: 
    - push
  environment:
    SONATYPE_GPG_KEYID:
      from_secret: sonatype_gpg_keyid
    SONATYPE_USERNAME:
      from_secret: sonatype_username
    SONATYPE_GPG_KEY:
      from_secret: sonatype_gpg_key
    SONATYPE_GPG_PASSWORD:
      from_secret: sonatype_gpg_password
    SONATYPE_PASSWORD:
      from_secret: sonatype_password
  commands:
  - apt-get update && apt-get install --yes --no-install-recommends gnupg2
  - chmod +x ./build.sh
  - ./build.sh

- name: deploy
  image: gradle:jdk8
  when:
    event:
    - promote
    target:
    - production
  commands:
  - apt-get update && apt-get install --yes --no-install-recommends gnupg2
  - chmod +x ./build.sh
  - ./build.sh
  - ./gradlew closeAndReleaseStagingRepository

